name: ai_calories_tracker
description: AI-powered calorie tracking app with food recognition and nutrition analysis

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  fl_chart: ^0.60.0

  flutter_dotenv: ^5.0.2
  # optionally for secure runtime storage:

  flutter_secure_storage: ^8.0.0
  # State management
  provider: ^6.1.1
  
  # Image handling
  image_picker: ^1.0.4
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # UI components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

  # Uncomment and add your assets here when you have them
  # assets:
  #   - assets/
  #   - assets/food_model.tflite
  #   - assets/labels.txt