name: ai_calories_tracker
description: AI-powered calorie tracking app with food recognition and nutrition analysis

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.0
  fl_chart: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

  # Uncomment and add your assets here when you have them
  # assets:
  #   - assets/
  #   - assets/food_model.tflite
  #   - assets/labels.txt